spec:
  containers:
    - name: metrics-app
      image: ghcr.io/cloudraftio/metrics-app:1.4
      ports:
        - containerPort: 8080
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: metrics-app-secret
              key: PASSWORD
